// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMHHG0RVZ_su5zHIAq02wY-ROLhScPV1U',
    appId: '1:871817356320:web:b9166395bb8a1277870845',
    messagingSenderId: '871817356320',
    projectId: 'eden-food-bd',
    authDomain: 'eden-food-bd.firebaseapp.com',
    storageBucket: 'eden-food-bd.firebasestorage.app',
    measurementId: 'G-J1XEHX1F44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXHXeTszJS1cO7uAoT88BMA2IukjMXXZ8',
    appId: '1:871817356320:android:11ee06f95ef348fe870845',
    messagingSenderId: '871817356320',
    projectId: 'eden-food-bd',
    storageBucket: 'eden-food-bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBJgZsW4kj-2H_I7feN7JocMN7A5Id1ts',
    appId: '1:871817356320:ios:b8489af0bd31213c870845',
    messagingSenderId: '871817356320',
    projectId: 'eden-food-bd',
    storageBucket: 'eden-food-bd.firebasestorage.app',
    iosBundleId: 'com.example.edenFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBJgZsW4kj-2H_I7feN7JocMN7A5Id1ts',
    appId: '1:871817356320:ios:b8489af0bd31213c870845',
    messagingSenderId: '871817356320',
    projectId: 'eden-food-bd',
    storageBucket: 'eden-food-bd.firebasestorage.app',
    iosBundleId: 'com.example.edenFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMHHG0RVZ_su5zHIAq02wY-ROLhScPV1U',
    appId: '1:871817356320:web:3cbf679b476dd951870845',
    messagingSenderId: '871817356320',
    projectId: 'eden-food-bd',
    authDomain: 'eden-food-bd.firebaseapp.com',
    storageBucket: 'eden-food-bd.firebasestorage.app',
    measurementId: 'G-B584STEFD9',
  );

}